# Generated by Django 4.2.6 on 2023-11-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.TextField()),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('ultima_vez', models.DateTimeField()),
                ('password', models.TextField()),
            ],
        ),
    ]
